name: Node Publish
run-name: Node Publish [${{ github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]

on:
  release:
    types: published
  push:
    branches: '*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Publish to npm
        if: github.event_name == 'release'
        run: npm publish --access public

      - name: Dry run
        if: github.event_name != 'release'
        run: npm publish --dry-run --access public
